#!/bin/sh
# Generated by claude/port/port.py; edit the generator, not this file.
cat <<'EOF'
{"hookSpecificOutput": {"hookEventName": "UserPromptSubmit", "additionalContext": "New task? Playbook match or rigor needed -> apply /poteto-mode. Casual turn or user opts out -> don't. Apply means the Skill tool, /poteto-mode. When its text is already in context, stay in it instead of invoking it again."}}
EOF
